services:
    postgresql:
        container_name: postgresql
        image: postgres:16.2
        env_file:
            - .env
        volumes:
            - data:/var/lib/postgresql/data
        networks:
            - transcendence-network
        restart: always
    adminer:
        container_name: adminer
        image: adminer:4.8.1
        depends_on:
           - postgresql
        ports:
            - "8080:8080"
        networks:
            - transcendence-network
        restart: always
    django:
        container_name: django
        build: ./django
        depends_on:
           - postgresql
        env_file:
            - .env
        volumes:
            - django:/usr/src/app
        networks:
            - transcendence-network
        restart: always
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "1024:80"
        depends_on:
           - django
        volumes:
            - static:/home/static
        networks:
            - transcendence-network
        restart: always
volumes:
    django:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./src/django
    static:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./src/static
    data: #postgresql
networks:
    transcendence-network:
        driver: bridge